---
- name: Set Ip Loopback
  hosts: all
  gather_facts: false

  tasks:
    - name: Create loopback
      ios_l3_interface:
        name: loopback {{ item.number }}
        ipv4: 10.1.{{ item.number }}.1/24
        state: present
      with_items:
        - { number: 1 }
        - { number: 2 }
        - { number: 3 }
    - name: Show loop
      ios_command:
        commands:
          - show ip int br
      register: show_loop

    - debug: var=show_loop.stdout_lines
       
