---
- name: Set Ip Loopback
  hosts: all
  gather_fact: false

  tasks:
    - name: Create vlan
      iso_13_interface:
        name: {{ item.name }}
        ipv4: {{ item.number}}
        state: present
      with_items:
        - { number: "10.1.1.1" , name: "loopback_1"}
        - { number: "10.1.2.1" , name: "loopback_2"}
        - { number: "10.1.3.1" , name: "loopback_3"}
    - name: Show loop
      ios_command:
        commands:
          - show ip int br
      register: show_loop

    - debug: var=show_loop.stdout_lines
       
